# Generated by Django 3.0.9 on 2020-08-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.User')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.User')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'chef',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id_recipe', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='recipe_img/')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Category')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Recipe')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Chef')),
            ],
            options={
                'db_table': 'coment',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='coments',
            field=models.ManyToManyField(related_name='recipes_coments', through='database.Coment', to='database.Chef'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='recipes_likes', to='database.Chef'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Chef'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('recipe_published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Recipe')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Chef')),
                ('sharers', models.ManyToManyField(related_name='shared_post', to='database.Chef')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='IngredientsRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=20)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Recipe')),
            ],
            options={
                'db_table': 'ingredients_recipe',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_chef', to='database.Chef')),
                ('to_chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_chef', to='database.Chef')),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.AddField(
            model_name='chef',
            name='followers',
            field=models.ManyToManyField(through='database.Follow', to='database.Chef'),
        ),
    ]
