# Generated by Django 3.0.9 on 2020-09-02 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ComentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Chef')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_coments', to='database.Post')),
            ],
            options={
                'db_table': 'coment_post',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='coments',
            field=models.ManyToManyField(related_name='post_coments', through='database.ComentPost', to='database.Chef'),
        ),
    ]
