# Generated by Django 3.0.9 on 2020-08-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200816_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='followers',
            field=models.ManyToManyField(related_name='followees', through='database.Follow', to='database.Chef'),
        ),
    ]
