# Generated by Django 3.0.9 on 2020-08-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200816_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='followers',
            field=models.ManyToManyField(through='database.Follow', to='database.Chef'),
        ),
    ]
