# Generated by Django 3.0.9 on 2020-08-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200816_2258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('from_chef', 'to_chef')},
        ),
    ]
