# Generated by Django 3.0.9 on 2020-08-16 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200816_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='from_chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_chefs', to='database.Chef'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='to_chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_chefs', to='database.Chef'),
        ),
    ]
