# Generated by Django 3.0.9 on 2020-08-16 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200816_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='from_chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_chef', to='database.Chef'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='to_chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_chef', to='database.Chef'),
        ),
    ]
