# Generated by Django 3.0.9 on 2020-08-17 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200816_2309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('to_chef', 'from_chef')},
        ),
    ]
