# Generated by Django 3.0.9 on 2020-08-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20200817_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='followers',
            field=models.ManyToManyField(related_name='followees', through='database.Follow', to='database.Chef'),
        ),
    ]
