# Generated by Django 3.0.9 on 2020-08-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
