# Generated by Django 3.0.9 on 2020-08-25 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20200824_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments_recipe', to='database.Recipe'),
        ),
    ]
