# Generated by Django 3.0.9 on 2020-08-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20200825_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_coments', to='database.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='recipe_likes', to='database.Chef'),
        ),
    ]
